steps:
- name: "gcr.io/kcc-clean/helm"
  args: ['upgrade', '--install', 'myapp', './myapp', '-f', './myapp/values-gke.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=automation-cluster'
options:
  workerPool:
    'projects/kcc-clean/locations/asia-southeast1/workerPools/PRIVATE_POOL_NAME'

